INSERT INTO users VALUES ('rulesincere', 'Louetta Pattee', 'password', '205A Pandan Loop 128442, Singapore', 'users', now());
INSERT INTO users VALUES ('omniscientsuggest', 'Lamont Eusebio', 'password1', '20 Havelock Road #01-00 Central Square, 059765, Singapore', 'users', now());
INSERT INTO users VALUES ('lizardburberry', 'Joaquina Copeland', 'password2', '75 Science Park #01-03 Cintech II, 118255, Singapore', 'users', now());
INSERT INTO users VALUES ('mildjackrabbit', 'Ayako Breece', 'password3', 'Queenstown Lutheran Church 709 Commonwealth Drive Singapore 149601, Singapore', 'users', now());
INSERT INTO users VALUES ('adddeveloper', 'Verna Gladfelter' , 'password4', '3 Temasek Boulevard #02-048 Suntec City Mall, 038983, Singapore', 'users', now());
INSERT INTO users VALUES ('costaricanforgive', 'Anneliese Estey', 'password5', '1 Changi South Street 2 Level 5, 486760, Singapore', 'users', now());
INSERT INTO users VALUES ('writesteady', 'Rosette Haverly', 'password6', 'Great World City 1 Kim Seng Promenade #15-07/#15-11 237994, Singapore', 'users', now());
INSERT INTO users VALUES ('cockytrouble', 'Davina Goya', 'password7', '26 Clementi Loop #01-55 Clementi Camp, 129817, Singapore', 'users', now());
INSERT INTO users VALUES ('lutzsecretive', 'Jacqulyn Buchannon', 'password8', 'Block 7 Pioneer Road North #01-51 Singapore 628459, Singapore', 'users', now());
INSERT INTO users VALUES ('forgetfulfix', 'Jill Uhlig', 'password9', '511 Kampong Bahru Road #03-02 Keppel Distripark, 099447, Singapore', 'users', now());
INSERT INTO users VALUES ('miniaturestupid', 'Jennefer Volpe', 'password10', '8 Neo Pee Teck Lane, 119034, Singapore', 'users', now());
INSERT INTO users VALUES ('tamarinkerching', 'Elias Harbor', 'password11', '36 Ayer Rajah Crescent #03-00, 139945, Singapore', 'users', now());
INSERT INTO users VALUES ('decisiveactor', 'Nam Tekulve', 'password12', 'Banyan tree building 211 upper bukit timah road, 588182, Singapore', 'users', now());
INSERT INTO users VALUES ('obeisantunsuitable', 'Terrilyn Holliman', 'password13', '1 Hougang Street 91 #01-41 HOUGANG FESTIVAL MARKET, 538692, Singapore', 'users', now());
INSERT INTO users VALUES ('foxbelated', 'Kindra Hockensmith', 'password14', '23 Defu Lane 4, 539421, Singapore', 'users', now());
INSERT INTO users VALUES ('cattlebounce', 'Marilynn Neri', 'password15', 'Block 77, Marine Drive, ,06-48 440077, Singapore', 'users', now());
INSERT INTO users VALUES ('racingoblongata', 'Deangelo Peake', 'password16', 'Blk 5000, Ang Mo Kio Ave 5 Techplace II, 03-04 569870, Singapore', 'users', now());
INSERT INTO users VALUES ('agitatedlabored', 'Danuta Loughran', 'password17', 'Shanker Tekri Udoygnagar, 478963 Jamnagar, Singapore', 'users', now());
INSERT INTO users VALUES ('subalternovercooked', 'Clarissa Poteat', 'password18', '445 Clementi Ave 3 #01-173, 120445, Singapore', 'users', now());
INSERT INTO users VALUES ('boorishinvincible', 'Alise Squires', 'password19', '22 Sin Ming Lane,16-76 Midview City Singapore 573969, Singapore', 'users', now());
